server.port: 8888
spring.cloud.config.server.git.uri: C:/gitrepos/rsconfig
---
spring:
  profiles.active: default
---
server:
  port: 8888
---
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    ## Hibernate Properties
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
management:
  endpoints.web.exposure.include: health,info,beans,env,refresh
server:
  port: 8888
---
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    ## Hibernate Properties
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
management:
  endpoints.web.exposure.include: health,info,beans,env,refresh
server:
  port: 8888
---
management:
  endpoints.web.exposure.include: health,info,beans,env